### ISSUE TITLE
Remove PTO app deployment from asppsvcs-generic

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/maintenance-project#6]
Copied from https://github.com/mozilla-itcloud/scl3-migration-project/issues/8

**Comment by gozer** [comment]
- [ ] Destroy PTO prod deployment #26 
- [ ] Destroy PTO stage deployment #27 
- [ ] Remove PTO from appscvs-generic deployment configuration #28

**Comment by gozer** [comment]
Done
